# Generated by Django 5.1.4 on 2026-06-12 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.TextField()),
                ('life_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('health_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('addon_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('life_attach_ratio_target', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('health_attach_ratio_target', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('addon_attach_ratio_target', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'targets',
                'indexes': [models.Index(fields=['scope'], name='targets_scope_08564b_idx'), models.Index(fields=['agent'], name='targets_agent_i_e85d0c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('scope', 'company')), models.Q(('agent__isnull', False), ('scope', 'agent')), _connector='OR'), name='targets_scope_agent_chk'), models.UniqueConstraint(condition=models.Q(('scope', 'company')), fields=('scope',), name='targets_company_unique'), models.UniqueConstraint(condition=models.Q(('scope', 'agent')), fields=('agent',), name='targets_agent_unique')],
            },
        ),
    ]
