# Generated by Django 5.1.4 on 2026-06-12 19:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_id', models.TextField(unique=True)),
                ('agent_name', models.TextField()),
                ('team_name', models.TextField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_name', models.TextField(blank=True, null=True)),
                ('deal_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('carrier', models.TextField()),
                ('product', models.TextField()),
                ('add_ons', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('add_on_amounts', models.JSONField(default=dict)),
                ('line_items', models.JSONField(default=list)),
                ('lead_source', models.TextField(blank=True, null=True)),
                ('cost_per_lead', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='teams.team')),
            ],
            options={
                'db_table': 'sales',
                'indexes': [models.Index(fields=['agent'], name='idx_sales_agent'), models.Index(fields=['team'], name='idx_sales_team'), models.Index(fields=['-sale_date'], name='idx_sales_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('deal_size__gte', 0), ('deal_size__isnull', True), _connector='OR'), name='sales_deal_size_check')],
            },
        ),
    ]
