# Generated by Django 5.1.4 on 2026-06-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_import_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='import_batch_id',
            field=models.UUIDField(blank=True, help_text='Set on bulk-imported sales so the batch can be rolled back.', null=True),
        ),
    ]
