# Generated by Django 5.1.4 on 2026-06-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_import_batch_id_db_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reporting_only',
            field=models.BooleanField(default=False, help_text='When true, sale is recorded for reporting only — no GHL contact sync.'),
        ),
    ]
