# Generated by Django 5.1.4 on 2026-07-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_reporting_only_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='estimated_payout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected agent check from product rates × advance months × monthly premium.', max_digits=12, null=True),
        ),
    ]
