# Generated by Django 5.1.4 on 2026-07-14 16:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('catalog', '0002_product_additional_pricing'),
        ('sales', '0007_payouts_and_comp_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentIncomeGoal',
            fields=[
                ('agent', models.OneToOneField(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='income_goal', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('annual_income_goal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_income_goals',
            },
        ),
        migrations.CreateModel(
            name='CompLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comp_levels',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('milestone_type', models.CharField(choices=[('first_sale', 'First sale'), ('sale_count', 'Nth sale'), ('submitted_ap', 'Submitted annual premium')], max_length=32)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Sale count or AP dollars depending on type.', max_digits=14)),
                ('cash_reward', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'onboarding_milestones',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrackerConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('foundation_weeks', models.PositiveSmallIntegerField(default=13)),
                ('beacon_weeks', models.PositiveSmallIntegerField(default=13)),
                ('phase_goal', models.DecimalField(decimal_places=2, default=Decimal('250000'), max_digits=14)),
                ('blended_income_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), help_text='Used for income-goal → business-needed estimate.', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracker_config',
            },
        ),
        migrations.CreateModel(
            name='AgentMilestoneAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='milestone_awards', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, db_column='sale_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_awards', to='sales.sale')),
                ('milestone', models.ForeignKey(db_column='milestone_id', on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='payouts.onboardingmilestone')),
            ],
            options={
                'db_table': 'agent_milestone_awards',
                'constraints': [models.UniqueConstraint(fields=('agent', 'milestone'), name='agent_milestone_awards_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProductCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('advance_months', models.PositiveSmallIntegerField(default=6)),
                ('rates', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_on', models.OneToOneField(blank=True, db_column='add_on_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='catalog.addon')),
                ('product', models.OneToOneField(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='catalog.product')),
            ],
            options={
                'db_table': 'product_commissions',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('add_on_id__isnull', True), ('product_id__isnull', False)), models.Q(('add_on_id__isnull', False), ('product_id__isnull', True)), _connector='OR'), name='product_commissions_xor_product_addon')],
            },
        ),
    ]
