# Generated by Django 5.1.4 on 2026-08-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0002_health_life_comp_tracks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complevel",
            options={"ordering": ["track", "sort_order", "name"]},
        ),
    ]
