# Generated by Django 5.1.4 on 2026-07-03 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('xp_required', models.PositiveIntegerField(default=0)),
                ('tier_type', models.CharField(choices=[('level', 'Level'), ('prestige', 'Prestige'), ('hof', 'Hall of Fame')], default='level', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'level_definitions',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=32)),
                ('agent_name', models.TextField(blank=True, default='')),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ev_created_ec5faf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveSmallIntegerField(default=0)),
                ('best_streak', models.PositiveSmallIntegerField(default=0)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='gamification_progress', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_at_level', to='gamification.leveldefinition')),
            ],
            options={
                'db_table': 'agent_progress',
                'indexes': [models.Index(fields=['-total_xp'], name='agent_progr_total_x_3ee90b_idx')],
            },
        ),
    ]
