# Generated by Django 5.1.4 on 2026-07-03 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='🏆', max_length=8)),
                ('metric', models.CharField(max_length=32)),
                ('period', models.CharField(default='weekly', max_length=16)),
                ('threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievement_definitions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('prize_description', models.TextField(blank=True, default='')),
                ('metric', models.CharField(default='revenue', max_length=32)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contests',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_key', models.CharField(default='all_time', max_length=32)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_earnings', to='gamification.achievementdefinition')),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_achievements',
                'indexes': [models.Index(fields=['agent'], name='agent_achie_agent_i_cfd203_idx'), models.Index(fields=['-earned_at'], name='agent_achie_earned__3d2f4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'achievement', 'period_key'), name='agent_achievements_unique_period')],
            },
        ),
    ]
