# Generated by Django 5.1.4 on 2026-07-08 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_achievementdefinition_contest_agentachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='🎁', max_length=8)),
                ('points_cost', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['sort_order', 'points_cost'],
            },
        ),
        migrations.AddField(
            model_name='agentprogress',
            name='points_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='point_trans_agent_i_955eca_idx'), models.Index(fields=['reason'], name='point_trans_reason_4e809e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_cost', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('agent_note', models.TextField(blank=True, default='')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='gamification.reward')),
            ],
            options={
                'db_table': 'redemptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='redemptions_status_f4f431_idx'), models.Index(fields=['agent', '-created_at'], name='redemptions_agent_i_20693d_idx')],
            },
        ),
    ]
