# Generated by Django 5.1.4 on 2026-07-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_reward_agentprogress_points_balance_pointtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('earning_rules', models.JSONField(blank=True, default=dict)),
                ('weekly_challenges', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamification_config',
            },
        ),
        migrations.AddField(
            model_name='achievementdefinition',
            name='points_reward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprogress',
            name='bonus_xp',
            field=models.IntegerField(default=0, help_text='Admin bonus XP added on top of sales-derived XP.'),
        ),
    ]
