# Generated by Django 5.1.4 on 2026-07-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_gamificationconfig_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team_id', help_text='Null = company-wide global contest visible to all agents.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['team', '-start_date'], name='contests_team_id_b4e1e2_idx'),
        ),
    ]
