# Generated by Django 5.1.4 on 2026-08-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0006_reward_team_scope"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reward",
            new_name="rewards_team_id_dfbcc4_idx",
            old_name="rewards_team_id_act_idx",
        ),
    ]
