# Generated by Django 5.1.4 on 2026-06-12 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GhlContact',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('location_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ghl_contacts',
                'indexes': [models.Index(fields=['user_id'], name='ghl_contact_user_id_73cc3b_idx'), models.Index(fields=['location_id'], name='ghl_contact_locatio_82d577_idx')],
            },
        ),
        migrations.CreateModel(
            name='GhlToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('location_id', models.TextField(blank=True, null=True)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('user_type', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ghl_tokens',
                'indexes': [models.Index(fields=['location_id'], name='ghl_tokens_locatio_aa1963_idx'), models.Index(fields=['expires_at'], name='ghl_tokens_expires_745662_idx')],
            },
        ),
        migrations.CreateModel(
            name='GhlWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('entity_id', models.TextField(blank=True, null=True)),
                ('entity_table', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ghl_webhook_logs',
                'indexes': [models.Index(fields=['status'], name='ghl_webhook_status_60c1c9_idx'), models.Index(fields=['-created_at'], name='ghl_webhook_created_639e4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GhlUser',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('location_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(blank=True, db_column='app_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghl_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ghl_users',
                'indexes': [models.Index(fields=['app_user'], name='ghl_users_app_use_c09d6f_idx'), models.Index(fields=['location_id'], name='ghl_users_locatio_63118f_idx')],
            },
        ),
    ]
