# Generated by Django 5.1.4 on 2026-06-12 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='team_managers', to='teams.team')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='team_manager_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_managers',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['manager'], name='teams_manager_20eeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='teammanager',
            index=models.Index(fields=['team'], name='team_manage_team_id_812eca_idx'),
        ),
        migrations.AddIndex(
            model_name='teammanager',
            index=models.Index(fields=['user'], name='team_manage_user_id_bfbdc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammanager',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='team_managers_team_id_user_id_key'),
        ),
    ]
