# Generated by Django 5.1.4 on 2026-06-12 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'add_ons',
                'indexes': [models.Index(fields=['active'], name='add_ons_active_8f2dd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('carrier_type', models.TextField(default='health')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carriers',
                'indexes': [models.Index(fields=['active'], name='carriers_active_2aec92_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_sources',
                'indexes': [models.Index(fields=['active'], name='lead_source_active_129699_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(blank=True, db_column='carrier_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.carrier')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['active'], name='products_active_20e15c_idx'), models.Index(fields=['carrier'], name='products_carrier_f94545_idx')],
                'constraints': [models.UniqueConstraint(fields=('carrier', 'name'), name='products_carrier_name_unique')],
            },
        ),
    ]
