# Generated by Django 5.1.4 on 2026-06-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_users_email_9c7e62_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['user'], name='login_token_user_id_baf733_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['expires_at'], name='login_token_expires_133cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='user_roles_user_id_05df60_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='user_roles_role_582040_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='user_roles_user_id_role_key'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['team'], name='profiles_team_id_22c1e2_idx'),
        ),
    ]
