# Generated by Django 5.1.4 on 2026-07-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('payouts', '0001_payouts_and_comp_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comp_level',
            field=models.ForeignKey(blank=True, db_column='comp_level_id', help_text='Hidden from other agents; drives product payout rates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='payouts.complevel'),
        ),
    ]
